eureka:
  instance:
    prefer-ip-address: true
    hostname: host.docker.internal
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      # defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
